### ISSUE TITLE
Replace Q with L

### ISSUE THREAD

**Issue by blackjersey** [karai17/Ente-Isla#1]
Kindly replace Q with L

**Comment by karai17** [comment]
What do you mean?

**Comment by blackjersey** [comment]
English Alphabet:

ABCDEFGHIJKLMNOPQRSTUVWXYZ

Ente Islan:

AZYXEWVTISRLPNOMQKJHUGFDCB

I replaced it in your jQuery but to be honest, the translated words are wrong according to this:

https://www.youtube.com/watch?v=c1OZJk0j20w&t=264s

**Comment by karai17** [comment]
Ah, I see the issue here. My translator is for the Japanese dub which was
just a straight reversal of the consanents whereas it seems like the
FUNimation dub used a slightly more complex letter swap to make the
language sound a bit more fluid.

https://youtu.be/ybzRecomoUw?t=224


---
Landon Manning
lmanning17@gmail.com

**Comment by blackjersey** [comment]
Ah... now I understand.  Your translator is very good nonetheless! Me and my daughter just got into it lol. The way FUNimation did it is a bit confusing for us. In the YT link I provided, she said "WORLD" and it became "WROB". Not sure if I undertand if she said "WORLD" or "WORD" really and that's why we are confused.

**Comment by karai17** [comment]
Yeah, I think she said "WROB". She definitely put more effort into the
language than the original Japanese team which is why it sounds fairly
humanistic and even a bit romantic (latin). However, I personally like the
sharp, guteral aspect of the Japanese version as it sounds less humanistic
which gives the "daemonic" aspect more strength. Either way, it's a really
interesting anime and I hope you and your daughter enjoy it. :)


---
Landon Manning
lmanning17@gmail.com

**Comment by blackjersey** [comment]
Will do. And thanks again for making this!
